# Build arguments
ARG SOURCE_CODE=.

# Use ubi8/go-toolset as base image
FROM registry.access.redhat.com/ubi8/go-toolset:1.21@sha256:742ae6ec1aef3e7faae488c47695fb64964d342aefecf52d23bd9d5e6731d0b6 as builder

ARG TARGETOS
ARG TARGETARCH

## Build args to be used at this step
ARG SOURCE_CODE

WORKDIR /opt/rhods

# Copy the Go Modules manifests
COPY ${SOURCE_CODE}/notebook-controller ./notebook-controller

# This is necessary because the Jupyter controller now depends on
# components/common
COPY ${SOURCE_CODE}/common ./common

# Update building workdir
WORKDIR /opt/rhods/notebook-controller

## Build the odh-notebook-controller
USER root

# Build
RUN  CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -tags strictfipsruntime -a -o ./bin/manager main.go

# Use ubi8/ubi-minimal as base image
FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:c38cc770631788157f8ea989df65ff30359c9f8af3246fef244b32caed9d5862

## Install additional packages
RUN microdnf install -y shadow-utils &&\
    microdnf clean all

## Create a non-root user with UID 1001
RUN useradd --uid 1001 --create-home --user-group --system rhods

## Set workdir directory to user home
WORKDIR /home/rhods

COPY --from=builder \
      /opt/rhods/notebook-controller/bin/manager \
      /manager

## Switch to a non-root user
USER 1001:0

ENTRYPOINT [ "/manager" ]

LABEL com.redhat.component="odh-notebook-controller-container" \
      name="managed-open-data-hub/odh-notebook-controller-rhel8" \
      description="odh-notebook-controller" \
      summary="odh-notebook-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-notebook-controller" \
      io.k8s.description="odh-notebook-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
